#include "Pixels.h"

namespace slag
{
    PixelAspectFlags SLAG_PIXEL_ASPECTS[]
    {
        PixelAspectFlags::NONE_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::DEPTH_FLAG | PixelAspectFlags::STENCIL_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::DEPTH_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::DEPTH_FLAG | PixelAspectFlags::STENCIL_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::DEPTH_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG,
        PixelAspectFlags::COLOR_FLAG
    };

    PixelAspectFlags Pixel::aspectFlags(PixelFormat format)
    {
        return SLAG_PIXEL_ASPECTS[static_cast<uint32_t>(format)];
    }
} // slag
